// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"
)

type Querier interface {
	AddTaskDependency(ctx context.Context, arg AddTaskDependencyParams) error
	CompleteTask(ctx context.Context, arg CompleteTaskParams) (Task, error)
	CountTasks(ctx context.Context, arg CountTasksParams) (CountTasksRow, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteTask(ctx context.Context, arg DeleteTaskParams) error
	GetDependentTasks(ctx context.Context, arg GetDependentTasksParams) ([]Task, error)
	GetRecentlyCompletedTasks(ctx context.Context, arg GetRecentlyCompletedTasksParams) ([]Task, error)
	GetTask(ctx context.Context, arg GetTaskParams) (Task, error)
	GetTaskDependencies(ctx context.Context, arg GetTaskDependenciesParams) ([]Task, error)
	GetTasksByTag(ctx context.Context, arg GetTasksByTagParams) ([]Task, error)
	GetTasksWithinDateRange(ctx context.Context, arg GetTasksWithinDateRangeParams) ([]Task, error)
	GetUser(ctx context.Context, email string) (User, error)
	ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error)
	RemoveTaskDependency(ctx context.Context, arg RemoveTaskDependencyParams) error
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error)
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
}

var _ Querier = (*Queries)(nil)
